[package]
name = "bevy_mic"
version = "0.1.0"
edition = "2021"

[dependencies]
# Bevy
bevy_app = "0.13.0"
bevy_audio = "0.13.0"
bevy_ecs = "0.13.0"

# Microphone interface
cpal = "0.15.3"

[dev-dependencies]
bevy = "0.13.0"
