[package]
name = "bevy_mic"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Bevy
bevy_app.workspace = true
bevy_audio.workspace = true
bevy_ecs.workspace = true

# Microphone interface
cpal = "0.15.3"
