[package]
name = "bevy_audio_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
# Bevy
bevy_app.workspace = true
bevy_asset.workspace = true
bevy_audio.workspace = true
bevy_reflect.workspace = true

crossbeam-queue = "0.3.11"

[dev-dependencies]
bevy.workspace = true
